# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13df28b7cff1afe87b1e9e327c91dbf28e6189c091d4bb2c5964dd9aa03d20bf596a06a279491d3e87b00b038c5f39d965c00432d5f007789e973d374e9c11ba

test:
  secret_key_base: 0136536bd6b322bd26402cb1d31ebf2b0944d1ea577e1b214af3d36aefb801506c1c6e8dedaa0e2e890c42f039b0b61cec597104263e34a128aab82d7f4e464c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
